---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - apps.demo.com
  resources:
  - simpledemoes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.demo.com
  resources:
  - simpledemoes/finalizers
  verbs:
  - update
- apiGroups:
  - apps.demo.com
  resources:
  - simpledemoes/status
  verbs:
  - get
  - patch
  - update
