# permissions for end users to view simpledemoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: simple
    app.kubernetes.io/managed-by: kustomize
  name: simpledemo-viewer-role
rules:
- apiGroups:
  - apps.demo.com
  resources:
  - simpledemoes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.demo.com
  resources:
  - simpledemoes/status
  verbs:
  - get
