apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .ObjectMeta.Name }}
  namespace: {{ .ObjectMeta.Namespace }}
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Spec.Expose.IngressDomain }}
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: {{ .ObjectMeta.Name }}
                port:
                  number: {{ .Spec.Port }}
