apiVersion: v1
kind: Service
metadata:
  name: {{ .ObjectMeta.Name }}
  namespace: {{ .ObjectMeta.Namespace }}
spec:
  type: NodePort
  selector:
    app: {{ .ObjectMeta.Name }}
  ports:
    - port: {{ .Spec.Port }}
      targetPort: {{ .Spec.Port }}
      nodePort: {{ .Spec.Expose.NodePort }}
