apiVersion: v1
kind: Service
metadata:
  name: {{ .ObjectMeta.Name }}
  namespace: {{ .ObjectMeta.Namespace }}
spec:
  selector:
    app: {{ .ObjectMeta.Name }}
  ports:
    - protocol: TCP
      port: {{ .Spec.Port }}
      targetPort: {{ .Spec.Port }}
